# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.18.4

# Mod Properties
mod_version=1.0.0
maven_group=polar.ru
archives_base_name=lavanda

# Dependencies
fabric_version=0.119.4+1.21.4
jna_version=5.14.0
websocket_version=2.14
lombok_version=1.18.36
